# Generated by Django 5.2.9 on 2025-12-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_location_venue_space'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_renter',
        ),
        migrations.AlterField(
            model_name='space',
            name='area_height',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='space',
            name='area_width',
            field=models.FloatField(default=1),
        ),
    ]
