# Generated by Django 5.2.9 on 2025-12-12 03:59

import api.utils.check_map_url
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_user_is_renter_alter_space_area_height_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='location',
        ),
        migrations.RemoveField(
            model_name='space',
            name='area_height',
        ),
        migrations.RemoveField(
            model_name='space',
            name='area_width',
        ),
        migrations.AddField(
            model_name='space',
            name='amenities_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='space',
            name='space_height',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='space',
            name='space_width',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='venue',
            name='address',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='venue',
            name='country',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='google_map_link',
            field=models.URLField(blank=True, max_length=500, validators=[api.utils.check_map_url.validate_google_maps_url]),
        ),
        migrations.AddField(
            model_name='venue',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='space',
            name='cleaning_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='space',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='space',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
