# Generated by Django 5.2.9 on 2025-12-12 15:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_item_remove_venue_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='space',
            old_name='price_per_hour',
            new_name='price_per_day',
        ),
        migrations.RemoveField(
            model_name='space',
            name='booking_step_minute',
        ),
        migrations.RemoveField(
            model_name='space',
            name='minimum_booking_minute',
        ),
        migrations.AlterField(
            model_name='space',
            name='space_height',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='space',
            name='space_width',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
