# Generated by Django 5.2.9 on 2025-12-13 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_amenity_booking_review_spaceamenity_and_more'),
        ('api', '0006_rename_price_per_hour_space_price_per_day_and_more'),
    ]

    operations = [
    ]
