# Generated by Django 5.2.9 on 2025-12-13 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_merge_20251212_1011'),
        ('api', '0007_merge_20251213_1624'),
    ]

    operations = [
    ]
