# Generated by Django 5.2.9 on 2025-12-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20251213_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_host',
        ),
        migrations.AlterField(
            model_name='venue',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='venue',
            name='province',
            field=models.CharField(max_length=100),
        ),
    ]
