# Generated by Django 5.2.9 on 2025-12-14 16:29

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_user_is_host_alter_venue_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='cleaning_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='space',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
