# Generated by Django 5.2.9 on 2025-12-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_space_cleaning_fee_alter_space_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='venue',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='unique_venue_name_per_owner'),
        ),
    ]
