# Generated by Django 5.2.9 on 2025-12-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_venue_unique_venue_name_per_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
