# Generated by Django 5.2.9 on 2025-12-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_venue_is_active'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='venue',
            name='unique_venue_name_per_owner',
        ),
        migrations.AddConstraint(
            model_name='venue',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('name', 'owner'), name='unique_active_venue_name_per_owner'),
        ),
    ]
