# Generated by Django 5.2.9 on 2025-12-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_venue_unique_venue_name_per_owner_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='review',
            name='api_review_venue_i_4f257f_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='api_review_reviewe_e228b5_idx',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='review',
            name='venue',
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['booking'], name='api_review_booking_468ef1_idx'),
        ),
    ]
